apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: inridemart
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: inridemart
  SPRING_DATASOURCE_PASSWORD: replace-me
  JWT_SECRET: replace-with-strong-32-byte-minimum-secret

